export const ErrorCode = {
  // Auth Errors
  AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_TOKEN_NOT_FOUND: "AUTH_TOKEN_NOT_FOUND",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_UNAUTHORIZED_ACCESS: "AUTH_UNAUTHORIZED_ACCESS",
  AUTH_TOO_MANY_ATTEMPTS: "AUTH_TOO_MANY_ATTEMPTS",

  // Access Control
  ACCESS_FORBIDDEN: "ACCESS_FORBIDDEN",
  ACCESS_UNAUTHORIZED: "ACCESS_UNAUTHORIZED",

  // Validation Errors
  VALIDATION_ERROR: "VALIDATION_ERROR",
  MISSING_REQUIRED_FIELDS: "MISSING_REQUIRED_FIELDS",

  // Book Errors
  BOOK_NOT_FOUND: "BOOK_NOT_FOUND",

  // Review Errors
  REVIEW_NOT_FOUND: "REVIEW_NOT_FOUND",

  // User
  USER_NOT_FOUND: "USER_NOT_FOUND",

  // System / Generic Errors
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;

export type ErrorCodeType = keyof typeof ErrorCode;
